export const SIGNED_IN = 'SIGNED_IN';
export const SIGNED_OUT = 'SIGNED_OUT';
export const UPDATE_USER = 'UPDATE_USER';

export const STREAM_DELETED = 'STREAM_DELETED';
export const STREAM_UPDATED = 'STREAM_UPDATED';
export const STREAM_CREATED = 'STREAM_CREATED';
export const STREAM_FETCHED = 'STREAM_FETCHED';
export const STREAMS_FETCHED = 'STREAMS_FETCHED';


export const STREAM_CREATE_BEGIN = 'STREAM_CREATE_BEGIN';
export const STREAM_CREATE_SUCCESS = 'STREAM_CREATE_SUCCESS';
export const STREAM_CREATE_FAILURE = 'STREAM_CREATE_FAILURE';